### ISSUE TITLE
ΠΤΥΧΙΑΚΗ ΕΡΓΑΣΙΑ - ΑΠΟΡΙΑ

### ISSUE THREAD

**Issue by apostoloskp** [epidrome/epidrome#1]
Καλησπέρα σας κ. Χωριανόπουλε.

Ονομάζομαι Απόστολος Καμπλιώνης με ΑΜ: 2015121, δε ξέρω αν με θυμάστε από τα εργαλεία συνάντησης στo μάθημα SW κατά την εαρινή περίοδο 2021.

Ο λόγος που απευθύνομαι σε εσάς, είναι η πιθανότητα εκπόνησης πτυχιακής εργασίας με την ομάδα σας.

Συγκεκριμένα, ήθελα να ρωτήσω ως προς το πόσο επηρεάζει η βαθμολογία στα μαθήματα σας (HCI:6, SW:8) και σύμφωνα με τις οδηγίες και έχοντας περάσει το μάθημα SW την εαρινή περίοδο 2021, τι ισχυει με την υποχρεωτική εργασία που αναφέρετε στις οδηγίες.

Εάν δηλαδή μοναδικη λυση αποτελει το να παρακολουθησω **ξανά** το μαθημα και να αναλαβω την εργασια ή προκειται να αλλαξει κατι οταν τα μαθηματα διεξαχθούν δια ζώσης, για να μπορέσω να δηλώσω πτυχιακή με την ομάδα σας.

Ευχαριστώ εκ των προτέρων

**Comment by epidrome** [comment]
ευχαριστώ για το ενδιαφέρον, ο βαθμός στο λογισμικό είναι σίγουρα ικανοποιητικός για μια πτυχιακή

σύμφωνα με τις παρακάτω οδηγίες άνοιξε θέμα στο αντίστοιχο αποθετήριο για γίνει περισσότερη συζήτηση
https://github.com/courses-ionio/thesis/issues/41

**Comment by apostoloskp** [comment]
Ευχαριστώ και εγώ για την ανταπόκριση.
Το ότι δεν ανέλαβα την υποχρεωτική εργασία που αναφέρετε επηρεάζει τη δυνατότητα να πάρω πτυχιακή με τον ομάδα σας?
